# Generated by Django 5.1.7 on 2025-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_customuser_name_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
