# Generated by Django 5.1.7 on 2025-03-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='place',
            field=models.CharField(choices=[('todo', 'To Do'), ('progress', 'In Progress'), ('feedback', 'Await Feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
