# Generated by Django 5.1.7 on 2025-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.JSONField(default=dict),
        ),
    ]
