# Generated by Django 5.1.7 on 2025-04-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_category_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryColor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
